# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev libffi-dev python3-dev

COPY csfloat_server.py .

# Install Python dependencies
RUN pip install --no-cache-dir python-dotenv httpx mcp

# Default command to run the MCP server over stdio
CMD ["python", "csfloat_server.py"]
