# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim
WORKDIR /app

# Install Python dependencies
RUN pip install --no-cache-dir python-dotenv httpx fastmcp

# Copy application source
COPY csfloat_server.py ./

# Expose stdio via MCP sidecar
CMD ["python", "csfloat_server.py"]
